package demo;

public class Test {
	
	public static void main(String[] args) {
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
		System.out.println("xxxxxx");
	}

}
